version: '3.8'

networks:
  monitor-net:
    driver: bridge

services:
  db:
    #image: postgres:15.3
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DMD_DB_POSTGRES_PASS}
    ports:
      - '127.0.0.1:${DMD_DB_POSTGRES_PORT}:5432'
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    networks:
      - monitor-net

  pgadmin:
    build: ./pgadmin 
    ports:
      - '127.0.0.1:3002:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=nobody@bit.diamonds
      - PGADMIN_DEFAULT_PASSWORD=${DMD_DB_POSTGRES_PASS}
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --appendonly yes
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  express:
    build: ./express
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD=${DMD_DB_POSTGRES_PASS}
      - REDIS_URL=redis://redis:6379
      - RPC_URL=${RPC_URL_DOCKER}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis
    networks:
      - monitor-net
